module.exports = {
  CONFIRM_USER: "CONFIRM_USER",
  USER_CONNECTED: "USER_CONNECTED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  ROOM_WELCOME: "ROOM_WELCOME",
  LOGOUT: "LOGOUT",
  // 🔥 新增功能
  PRIVATE_MESSAGE: "PRIVATE_MESSAGE", // 私聊
  TYPING: "TYPING",                   // 正在输入
  STOP_TYPING: "STOP_TYPING",          // 停止输入,
  NEW_NOTIFICATION: "NEW_NOTIFICATION", // <--- 必须新增这一行
};