// migrate_sessions.js
import { connect } from 'mongoose';
import { find, updateMany } from '../models/Chat';
import Conversation from '../models/Conversation';
import { find as _find } from '../models/User'; // 假设你有 User 模型

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/你的数据库名';

// 生成 UUID 的简单函数
const uuidv4 = () => {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    var r = (Math.random() * 16) | 0,
      v = c == 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
};

const migrate = async () => {
  try {
    await connect(MONGO_URI);
    console.log('🔥 数据库连接成功，开始迁移...');

    // 1. 找出所有“有聊天记录”但“没在 Conversation 表里注册过”的用户
    // 这里我们简单点：遍历所有用户，给每个用户处理旧数据
    const users = await _find({});

    for (const user of users) {
      const userId = user._id;
      const aiRoomName = `ai_session_${userId}`;

      // 2. 查找该用户所有属于 AI 房间且没有 sessionId 的消息
      const legacyMessages = await find({
        room: aiRoomName,
        sessionId: { $exists: false } // 或者 $eq: null
      });

      if (legacyMessages.length === 0) {
        console.log(`用户 ${user.displayName} (ID: ${userId}) 没有旧数据，跳过。`);
        continue;
      }

      console.log(`🔄 发现用户 ${user.displayName} 有 ${legacyMessages.length} 条旧消息，正在归档...`);

      // 3. 创建一个“历史归档”会话
      const archiveSessionId = uuidv4();

      const archiveConversation = new Conversation({
        user: userId,
        sessionId: archiveSessionId,
        title: '😄初次对话聊天记录', // 给个显眼的名字
        isTitleAutoGenerated: true, // 标记为已生成，防止 AI 以后改名
        lastActiveAt: new Date() // 设为现在，让它排在最前
      });

      await archiveConversation.save();

      // 4. 批量更新 Chat 记录
      const result = await updateMany(
        {
          room: aiRoomName,
          sessionId: { $exists: false }
        },
        {
          $set: { sessionId: archiveSessionId }
        }
      );

      console.log(`✅ 用户 ${user.displayName} 归档完成！更新了 ${result.modifiedCount} 条消息。`);
    }

    console.log('🎉 所有迁移工作完成！');
    process.exit(0);
  } catch (err) {
    console.error('❌ 迁移失败:', err);
    process.exit(1);
  }
};

migrate();
