import { Schema, model } from 'mongoose';

const ConversationSchema = new Schema(
  {
    // 关联用户
    user: { type: Schema.Types.ObjectId, ref: 'users', required: true },

    // 🔥 核心：前端生成的 UUID，用于串联 Chat 记录
    sessionId: { type: String, required: true, unique: true, index: true },

    // 会话标题 (AI 自动生成)
    title: { type: String, default: '新对话' },

    // 标记是否已经自动生成过标题 (避免反复修改)
    isTitleAutoGenerated: { type: Boolean, default: false },

    // 用于列表排序：每次说话都会更新这个时间
    lastActiveAt: { type: Date, default: Date.now }
  },
  { timestamps: true }
);

export default model('conversation', ConversationSchema);
